### PR TITLE
New Characters and Weapons from recent patches

### PR DESCRIPTION
**Pull request by Groovman**

### CODE REVIEW

**Comment by kagekiyo7** [comment]
TODO:
- support ability 2: 
Lelouch Lamperouge, Suzaku Kururugi

**Comment by Groovman** [comment]
> TODO:
> 
> * support ability 2:
>   Lelouch Lamperouge, Suzaku Kururugi

Don't you mean Kallen and Suzaku? Lulus 2nd ability is already done.

**Comment by kagekiyo7** [comment]
Oh, I noticed now, but The maximum amount was different. (Max 10)

**Comment by Groovman** [comment]
> Oh, I noticed now, but The maximum amount was different. (Max 10)
> http://gbf-verification.blog.jp/archives/19282248.html

Done

**Comment by kagekiyo7** [comment]
OK. it is perfect. 
Please merge if there are no other problems.

>Cygames why write Big Boost when it is just M

true

**Pull request merged**
