### PR TITLE
Update Sun-Touched Paradise field effect

### PR DESCRIPTION
**Pull request by Groovman**
Move Sun-Touched Paradise to Unique modifier

see: https://gbf.wiki/Alanaan

### CODE REVIEW

**Comment by kei-gbf** [comment]
@Groovman 
thx, It's clean and easy to find info now.

I did not notice this, Can you fix the amount
- [ ] ATK up 20% (DEF down 25%)
  - [x] gamewith also had same values 20%/25%

**Comment by Groovman** [comment]
@kei-gbf 
Updated the modifier value and added the Def Down effect.

**Comment by kei-gbf** [comment]
oh I was not going to mention debuff

we need this ? because currently it does not check debuff limit.

use-case scenario:
Users set debuff 50% as usually and watch the changes by Sun-Touched Paradis on/off
but they have to change debuff amount to be max 50%

it's not simple just limit 50%, because there are over limit debuff.

for now, just ATK 20% is ok

**Comment by Groovman** [comment]
> oh I was not going to mention debuff
> 
> we need this ? because currently it does not check debuff limit.
> 
> use-case scenario:
> Users set debuff 50% as usually and watch the changes by Sun-Touched Paradis on/off
> but they have to change debuff amount to be max 50%
> 
> it's not simple just limit 50%, because there are over limit debuff.
> 
> for now, just ATK 20% is ok

Done

**Comment by kei-gbf** [comment]
- [x] Checked the amount in result/skill display.

----
- update translation tooltip shown old info 25% gain normal buff
  - Are there similar effect text? (if there was then follow the format)

烈日の楽園説明
  - [ ] FIXME: "All Allies ~~gain 25% normal buff~~, and can deal critical hits regardless of element. (Alanaan)"


```diff
- "ja": "対象の属性に関係なく味方のクリティカルが発生し、味方の通常攻刃25%UP。(アラナン)",
+ "ja": "対象の属性に関係なく味方のクリティカルが発生し、味方の攻撃力上昇 別枠乗算20% (アラナン)"
```

**Comment by Groovman** [comment]
> * [x]  Checked the amount in result/skill display.
> 
> * update translation. tooltip shown old info 25% gain normal buff
>   
>   * Are there similar effect text? (if there was then follow the format)
> 
> 烈日の楽園説明
> 
> * [ ]  FIXME: "All Allies ~gain 25% normal buff~, and can deal critical hits regardless of element. (Alanaan)"
> 
> ```diff
> - "ja": "対象の属性に関係なく味方のクリティカルが発生し、味方の通常攻刃25%UP。(アラナン)",
> + "ja": "対象の属性に関係なく味方のクリティカルが発生し、味方の攻撃力上昇 別枠乗算20% (アラナン)"
> ```

Done

**Pull request merged**
