### PR TITLE
Fix composite support lookup logic for nest

### PR DESCRIPTION
**Pull request by kei-gbf**
- composite support can be nest now

- eachSupport function is moved to support.js

- Add unit test for flattenCompositeSupport
  - Limit maximum number of recursion (invalid case)

- Skip dupplicated support within a composite

Implementation details: (Flatten algorithm for nested data)

The flatten logic process the nested composite without recursive call.
The function does not consume function call stack,
make it possible by stack of generator object to process in a flat loop.

----

- [x] TODO: Fix unit test in TravisCI / Add polyfill for Generator

### CODE REVIEW

**Comment by kei-gbf** [comment]
re-introduce the support module

- it was implemented for #259 and the patch is https://github.com/h-yasha/motocal/pull/8

that that module solve mainly two issues

----
### no duplicate clone code for isConsideredInAverage

```js
if (totals[key].isConsideredInAverage) {
    for (var key2 in totals) {
        totals[key2]["charaHaisui"] += charaHaisuiValue
    }
} else {
    totals[key]["charaHaisui"] += charaHaisuiValue
}
```

support logic has a lot similar code that if isConsideredInAverage for ...
then duplicated code for else case.

support_range.js can resolve it, processing isConsideredInAverage flag internally.

```js
for (let [name, chara] of range.all(totals, key)) {
    chara["charaHaisui"] += charaHaisuiValue;
}
```

----
### share support logic code by composite support definition

fall through approach in logic code will break when it's more than three cases.
composite support can solve the situation.

```js
// in global_logic.js
case "normalSupportKonshin_hpDebuff":
    totals[key]["HPdebuff"] += support.hpDebuff;
    // falls through
case "normalSupportKonshin":
```

it was quick/easy solution when implemented the "normalSupportKonshin_hpDebuff".
that can be

```
// in global_const.js
"normalSupportKonshin_hpDebuff": {
    "name": "...",
    "type": "composite",
    "value": [
        {ID: "normalSupportKonshin"},
        {type: "hpDebuff", range: "own", value: 0.15}
    ]
}
```

eachSupport() can generate two or more support for the composite type case.

the composite support sample is implemented only:
- mamorubeshi_sono_egao
- mamoritai_kono_egao

a lot support can be replaced with this module.
This patch provides the potential only, but I will not touch the support logic/const.
(testing a lot support change will take a time for review, I separate the task PR)

**Comment by kei-gbf** [comment]
Problem: Travis report test failed

Details:
This problem CI failed was because of the Test environment gap.
test script run on the node engine, not same as production code they are run on browser.


Solutions:
- [ ] upgrade node version to 10.x
  - need to research issues, it require site admins to upgrade node too.
- [ ] Babel transpile or add polyfill plugin for Jest (Babel config)
  - I should choose this solution, it's only for test environment (devDependencies)

**Comment by OrkunKocyigit** [comment]
I don't support node server upgrade over this change. Running on my node 8.11 server resulted in success even at Travis Failing build so I don't really know what is the issue. I would support babel solution as developer environments are easier to update/setup.

**Comment by shinraminagi** [comment]
Hey, this commit broke the app: 1cc7a2c086f7ccc735b1204debb81d19abee87cf
You need 'require('./support')' in global_logic.js at least, but it cannot fix.

**Pull request merged**
