### PR TITLE
Github Pages Integration

### PR DESCRIPTION
**Pull request by OrkunKocyigit**
Demos
----
Prod: https://orkunkocyigit.github.io/motocal-prod/
Dev: https://orkunkocyigit.github.io/motocal-dev/

Following steps has to be done via org admin (aka not me):
https://help.github.com/articles/creating-an-access-token-for-command-line-use/
https://docs.travis-ci.com/user/environment-variables#defining-variables-in-repository-settings

### CODE REVIEW

**Comment by kei-gbf** [comment]
Personally I also use github pages as hosting
There are some issues, as I know: (it's not technical issues)

- [ ] Server load/save will not work
  - there are out of repo, can we disable the load/save? if it was not available.
  - I have compatible php scripts i used for test if anyone want to start server side,
   or can ask in discord someone had it in private repo.
- [ ] Github pages configuration there are three ways:
  - [ ] gh-pages branch (old undocumented way, but still works)
  - [ ] master branch
  - [ ] master branch ./docs folder
- [ ] License (downloaded images)
  -  In personal repo, it's personal responsibility.
  - We may need to discuss the legal risk if put downloaded images under "official" repo
    not sure cygames allow or not, at least license incompatible (not MIT license)
  - the main point here is it's on Motocal's official repo, we should avoid the risks to get warnings.
    it's less risk in personal repo. or there are choices to do in another repo or project.
  - you may have question about another data json etc, I agree that, I know what you feel the same.
    no one know the border. text data is ok or images data.
 - [ ] Download images request
  - [ ] can use cache?
    - I can work for the cache, if improve this point. by manage downloaded image list.
  - If download all new files always then it may be like a attack for the hosting server.
    the hosting server may kick those requests by Python script.
    - not about user-agent. we should avoid the risk they filters remote address.

----
Related "deploy" topics

we have "Heroku deploy" button ... I haven't use this so much, 
how about "Heroku Review Apps" ? it also do similar task?

CodeSandbox had issue on loading JSON files encoding,
(Japanese text letter broken, English is ok)
it's easy way for developer debug, but not suit for deploy to end users.

**Comment by OrkunKocyigit** [comment]
I completely forgot about licensing, I'll look for legal issues

**Comment by OrkunKocyigit** [comment]
This would bu under fair use in US and EU but Japan has no such law. I'll remove images (though by that logic weapon and character names also fall under those).

**Comment by kei-gbf** [comment]
@OrkunKocyigit 

For fair use, does it require update README or license text ? if github support multi license.
- case: someone who does not know the game,
  they may think those image file was under MIT license. (if they just watch github's license text)

Another issue deploy by travis task
forked repo also refer the same setting (deploy to official repo)
- [ ] "MotocalDevelopers/motocal-prod" also should be variable like a token?

----
How about other solution provide deploy script ? https://www.npmjs.com/package/gh-pages
"npm run deploy"  not by travis, users run the command and deploy to their forked repo.

**Comment by OrkunKocyigit** [comment]
@kei-gbf 
We use MIT and we are not license holder for GBF assets so no need to change license.

gh-pages repository name to variable is a fair request. I'll update it.

**Pull request closed without merging**
