### PR TITLE
Latest Patches, Opus Element skill, fixes

### PR DESCRIPTION
**Pull request by Groovman**
Added the Opus Element skill and the characters and weapons from the latest patches.

Also fixed the parenthesis that were wrong.

### CODE REVIEW

**Comment by kei-gbf** [comment]
@Groovman 

thx. can you see eachSkill in generateHaisuiData 
eachSkill(arm[i]) -> should be  arml[i] or arm

I noticed this may be another issue, I do not know where it's used.

**Comment by kagekiyo7** [comment]
Thank you as always!

Suggest(skill name):
Rename 属性攻撃力(大) to 進境(大)(最大時)

----
And, Please reply if you like
https://github.com/MotocalDevelopers/motocal/pull/172#issuecomment-488959688
https://github.com/MotocalDevelopers/motocal/pull/172#issuecomment-489340458

**Comment by Groovman** [comment]
@kei-gbf 
Haisui and Konshin are looking ok for me, arm instead of eachSkill(arm[i]) makes not much sense to because you want to iterate over the skills to find and recalc emnity and stamina.

**Comment by kei-gbf** [comment]
@Groovman 
was not a typo? because I saw var arm = arml[i];
I do not know what is arm[i] there, `i` changes every iteration.

```jsx
                // Weapon data calculation
                for (var i = 0; i < arml.length; i++) {
                    var arm = arml[i];

                    if (storedCombinations[j][i] === 0) continue;

                    for (let [skillname, element] of eachSkill(arm[i])) {
```

**Comment by Groovman** [comment]
@Groovman 
My bad I though you meant "eachSkill(arm[i])" to just "arm" not "eachSkill(arm[i])" to "eachSkill(arm)"

Yeah fixed that :)

**Comment by kei-gbf** [comment]
Ok, please! I was not sure it's typo or something. I did not notice the arm "l" 
I will close #189 duplicated

**Comment by Groovman** [comment]
@kei-gbf @kagekiyo7 
Can one just review it so I can press merge?

**Comment by kagekiyo7** [comment]
OK.
Before that, please fix Translation again.

opus-normalElement → 通常進境(大)(最大時)
opus-magnaElement → 方陣進境(大)(最大時)

**Pull request merged**
