### PR TITLE
Rewrite konshin calculation

### PR DESCRIPTION
**Pull request by kagekiyo7**
- Add a normal konshin S value
- Add a normal konshin LLL value
- Fix a omega haisui value

### CODE REVIEW

**Comment by Groovman** [comment]
Will check it today when I find time, just something I saw at first glance, the Ancestral value differs from
https://gbf.wiki/Weapon_Skills#ATK_up_as_HP_increases

Could you crosscheck it between your sources and what the the calculation results in the end?

**Comment by kagekiyo7** [comment]
Galilei's Insight was changed skill to "Stamina II"(=konshinLL) by game update.
https://gbf.wiki/Galilei's_Insight

Thorefore, It seem it's necessary to change skill of  Fediel's Spine assignment to konshinLLL.

**Comment by kagekiyo7** [comment]
OK!
image
image

**Comment by kagekiyo7** [comment]
I checked based on Hecate_mk2 tweet.
Calculation results look fine.

https://twitter.com/Hecate_mk2/status/1369797411971862534
https://twitter.com/Hecate_mk2/status/1117993240962093056

**Review by Groovman — APPROVED** [review]
LGTM!

Numbers look ok, I just added the changes to Galilei (and Taisai) so we don't have to remove a skill from the skilllist to prevent issues.

**Pull request merged**
