### PR TITLE
Add/Update Various Support Abilities. Also fix Djeeta's DMG Cap EM

### PR DESCRIPTION
**Pull request by h-yasha**
**EDIT: note https://github.com/MotocalDevelopers/motocal/pull/259#issuecomment-509559488**

~~**Progress is reflecting my _local_ copy. I'll refrain from pushing any update until I get it "OK".**~~
- [x] [Yaia](https://gbf.wiki/Yaia): (Support 1) 5% boost to ATK ~~and 10% boost to DEF~~ for all other allies. 20% / 20% boost to critical hit rate for all other allies.
- [x] [Yaia (Holiday)](https://gbf.wiki/Yaia_(Holiday)): (Support 1) 20% / 20% boost to critical hit rate for all other allies when Yaia is a main ally.
- [ ] [Beatrix (Themed)](https://gbf.wiki/Beatrix_(Themed)): (Support 1) Boost to critical hit rate based on how low HP is (Only activates when below 60%). [reference](https://docs.google.com/spreadsheets/d/1tmd7bBBPkXXbIiecMDEZapdyhjvnshbNlAraOlzDSmY/edit#gid=298937121). Disabled: https://github.com/MotocalDevelopers/motocal/pull/259#issuecomment-509314539
- [x] [Lancelot and Vane](https://gbf.wiki/Lancelot_and_Vane): (Support 2) Increase Aegis-type weapon skills' 'Boost to max HP' effect by 30%. [reference](https://docs.google.com/spreadsheets/d/1tmd7bBBPkXXbIiecMDEZapdyhjvnshbNlAraOlzDSmY/edit#gid=1706595677)
  - Expected that it boosts all type of "normal" and magna HP boost weapon skill. Looking into:
    - [Titan's Aegis](https://gbf.wiki/Broadsword_of_Earth).
    - [Goldslime's Aegis](https://gbf.wiki/Goldslime_Bell).
- [x] [Sturm](https://gbf.wiki/Sturm): (Support 1) 80% bonus Fire damage for single attacks and 30% bonus Fire damage for double attacks.
- [x] [Levin Sisters](https://gbf.wiki/Levin_Sisters): (Support 2) 15% Bonus Light DMG effect upon triple attack.
- [x] [Shiva](https://gbf.wiki/Shiva), [Europa](https://gbf.wiki/Europa), [Alexiel](https://gbf.wiki/Alexiel), [Grimnir](https://gbf.wiki/Grimnir), ~~realGrimnir~~ [Kokkoro](https://gbf.wiki/Kokkoro): Allies gain an additional 30%/15% boost to _x_ ATK when affected by _x_ ATK Up. (x: element)
- [x] [Aglovale](https://gbf.wiki/Aglovale): (Support 1) Elemental ATK UP & ca specs when affected by Elemental ATK UP 
- [x] [Heles (Wind)](https://gbf.wiki/Heles_(Wind)): (Support 1) 30% boost to Heles's ATK (normal) and 20% boost to C.A. Specs when affected by Wind ATK Up. (C.A. specs boost is in C.A. itself)
- [ ] [Ayer](https://gbf.wiki/Ayer):  (Support 1) Boost to double attack rate and damage cap based on how low HP is. Disabled: https://github.com/MotocalDevelopers/motocal/pull/259#issuecomment-509314539
    - Verification: Flat increases? Linear Increases? (Implemented Flat for now. although probably?? is linear.)
- [x] [Sara](https://gbf.wiki/Sara): (support 1) Boost to ATK as HP decreases. [reference](https://docs.google.com/spreadsheets/d/1tmd7bBBPkXXbIiecMDEZapdyhjvnshbNlAraOlzDSmY/edit#gid=1403186067)
- [x] [Olivia](https://gbf.wiki/Olivia): (Support 2) 10% boost to damage against Light foes (seraphic like) when Olivia has Dark ATK Up
- [x] [Conan Edogawa](https://gbf.wiki/Conan_Edogawa): (Support 2) Charge bar fills up 20% faster.
- [x] [Geisenborger](https://gbf.wiki/Geisenborger), [Wulf and Renie](https://gbf.wiki/Wulf_and_Renie): (Support 1, 1) charge bar speed 35% slower.
- [x] [Clarisse (Valentine)](https://gbf.wiki/Clarisse_(Valentine)): (Support 2) MC's charge bar fills up 20% faster
- [x] [Black Knight](https://gbf.wiki/Black_Knight) - (Support 2) max HP 10% UP
- [x] [Eugen (Grand)](https://gbf.wiki/Eugen_(Grand)):  (Support 2) Critical Damage Cap UP
- [x] [Silva (Light)](https://gbf.wiki/Silva_(Light)):  (Support 1) Light Allies Critical Damage Cap UP.
- [x] ~~[SSR Ladiva](https://gbf.wiki/Ladiva_(SSR)): (Support 2) 20% Boost to Max HP.~~ already implemented (although directly into `charaData.json`, check below).

Canceled:
- too complicated to implement in this PR:
    -  [Lyria](https://gbf.wiki/Lyria), [Sakura Kinomoto](https://gbf.wiki/Sakura_Kinomoto): (Support 1, 2) does not attack ~~(Sakura ougi no damage too)~~

<hr>

"Why Not"
- [x] [Carmelina](https://gbf.wiki/Carmelina), [Lennah](https://gbf.wiki/Lennah), and [Funf](https://gbf.wiki/Fif): Boost to Debuff Resistance 

<hr>

old support abilities changes/adapting:
- _Gain an additional 30% boost to Elemental buffs when affected by Elemental Buff._ 
    - [x] Will also reflect Party Buffs's Element Buff.
    - [x] _Gain an additional 30% boost to Elemental buffs when affected by Elemental Buff._ And similar type, will only be effective if element matches. (as in Shiva support ability will not activate for non fire units)
- [x] Fix: _Boost to ATK as HP decreases._ > Character Enmity Support Abilities (Jeanne D'Ark (Dark), Sara) values are invalid due to changes in `calcHaisuiValue` in adapting toward sklv15 > sklv20 addition.
- [x] Update `scripts/character_data_converter.py` with the changes that are not in there (support abilities implemented without updating it). _where changes were applied directly in_ `charaData.json`_._
    - [Karyl](https://gbf.wiki/Karyl) Support Ability 2
    - [Ladiva (SSR)](https://gbf.wiki/Ladiva_(SSR)) Support Ability 2
- [x] Update `txt_source/charaData.txt`, _once again, the changes were already implemented in_ `charaData.json`:
    - Add Sword Proficiency to [Jeanne D'Ark](https://gbf.wiki/Jeanne_d%27Arc)

### CODE REVIEW

**Comment by h-yasha** [comment]
Note from #246 
> support ability field will be DASupport, TASupport

**Comment by h-yasha** [comment]
- [ ] Proper translation/text.
- [ ] Clean up if needed.

**Comment by h-yasha** [comment]
TODO (would probably do in another PR, this one is already a bit too much):
- [ ] Add additional Support ability input field (like weapon skill's - calamitous covenant).
- [ ] Add support abilities that has "stacking"/etc. Like:
    - Kallen Kozuki, Hallessena, Charlotta (Light), etc...

**Comment by kei-gbf** [comment]
## Review Tasks

- [ ] translate changelog (I will update this comment)
  - [x] add wiki link to characters
    (English wiki, they has references to japanese wiki, other sites in Extra Data tab)
- [ ] make checklist for review

----
## 更新内容 (翻訳途中) in progress

- [ ] [ヤイア](https://gbf.wiki/Yaia) サポアビ1: 味方 ATK5%/DEF10%/クリティカル20%/20%UP
- [ ] [ヤイア (クリスマス)](https://gbf.wiki/Yaia_(Holiday)) サポアビ1: 味方クリティカルUP(20%/20%)
  - [ ] ヤイアがメインメンバーにいる時
- [ ] [ベアトリクス(水着)](https://gbf.wiki/Beatrix_(Themed)) サポアビ1: HP減少に応じてクリティカル率UP
- [ ] [ランスロット＆ヴェイン](https://gbf.wiki/Lancelot_and_Vane) サポアビ2: 守護スキルの効果UP
  - Titan's Aegis.
  - Goldslime's Aegis.
- [ ] [スツルム](https://gbf.wiki/Sturm) サポアビ1: SA 80%追撃 DA 30%追撃(火属性)
- [ ] [レヴィオン三姉妹](https://gbf.wiki/Levin_Sisters) サポアビ2: TA時に光属性追撃15%
- [ ] 味方全体、属性UPバフの効果量UP(30%/15%)
  - [ ] [シヴァ](https://gbf.wiki/Shiva)
  - [ ] [エウロペ](https://gbf.wiki/Europa)
  - [ ] [ブローディア](https://gbf.wiki/Alexiel) 
  - [ ] [グリームニル](https://gbf.wiki/Grimnir)
  - [ ] [コッコロ](https://gbf.wiki/Kokkoro)
- [ ] [アグロヴァル](https://gbf.wiki/Aglovale) サポアビ1: 属性UPの効果量アップ(自分のみ)
- [ ] [ヘルエス(風)](https://gbf.wiki/Heles_(Wind)) サポアビ1: 30% boost to Heles's ATK (normal) and 20% boost to C.A. Specs when affected by Wind ATK Up. (C.A. specs boost is in C.A. itself)
- [ ] [アイル](https://gbf.wiki/Ayer) サポアビ1 Boost to double attack rate and damage cap based on how low HP is.
Verification: Flat increases? Linear Increases? (Implemented Flat for now. although probably?? is linear.)
- [ ] [サラ](https://gbf.wiki/Sara) サポアビ1 Boost to ATK as HP decreases. reference
- [ ] [オリヴィエ](https://gbf.wiki/Olivia) サポアビ2: 10% boost to damage against Light foes (seraphic like) when Olivia has Dark ATK Up
- [ ] [江戸川コナン](https://gbf.wiki/Conan_Edogawa) サポアビ2: Charge bar fills up 20% faster.
- [ ] サポアビ: 奥義ゲージが溜まりにくい
  - [ ] [ガイゼンボルグ](https://gbf.wiki/Geisenborger)
  - [ ] [ウーフとレニー](https://gbf.wiki/Wulf_and_Renie)
  - [ ] 他キャラのチェック: プレデター(SR)、クビラ、(ルルーシュ、スザク、カレン)
- [ ] [クラリス(バレンタイン)](https://gbf.wiki/Clarisse_(Valentine)) サポアビ2: MC's charge bar fills up 20% faster
- [ ] [黒騎士](https://gbf.wiki/Black_Knight) サポアビ2: max HP 10% UP
- [ ] [リミテッド・オイゲン](https://gbf.wiki/Eugen_(Grand)) サポアビ2: Critical Damage Cap UP
- [ ] [シルヴァ(光)](https://gbf.wiki/Silva_(Light)) サポアビ1: Light Allies Critical Damage Cap UP.
- [ ] ~~[ファスティバ(SSR)](https://gbf.wiki/Ladiva_(SSR)) サポアビ2: 20% Boost to Max HP~~
  - [ ] charaData.json 内で直接実装済み? (check below)

----
TODO: translate
- [ ] Canceled
- [ ] "Why Not"
- [ ] old support abilities changes/adapting:

----
- [ ] Check Heles (Wind)
  - support description (I did not check code details yet, it's about PR comment)
    - I could not find info about C.A (ability? or fire heles?)
  - 真龍 ... translation (pronounce) for skill id, 
    - [ ] matatsu -> "shinryu" (but a bit confuse like 神龍 also shinryu/shenlong)
      matatsu is unusual. but ... I don't know if they speak the kanji in game, Heles fate story etc.

about reading/pronounce of the kanji
There were official confuse like 神威, 碧空, etc...
- Official support reply in email, they does not have specific answer
- Producer had told in stream, there are no official reading. but they used unusual reading in talk.
- Magazine(weekly famitsu) had the kanji reading article of granblue fantasy
  as I remember, around 4th anniversary

so I think English name is also ok. less confuse as ID it's not displayed anywhere.
it's ID stored in save data, we can't change old names, this is about new ID names.

**Comment by kei-gbf** [comment]
## Yaia and Yaia (Holiday)

- skill is similar but name has gap: mamoritai_kono_egao, critical_up_others_20_20
  - [ ] declare consts in close place with similar naming
    - like, "critical_up_others_20_20_atk_5", "critical_up_others_20_20"
    - or "mamoritai_kono_egao", "mamorubeshi_sono_egao"
  - ~~first I thought implementation cases with fallthrouth but atk 5 also has range others loop~~
  - [ ] same type and normalBuff: 0 for critical_up_others_20_20,
      then two supports can use same code.

I sketch piece of ideas (not tested code now)

```js
const range_others = (totals, key) => Object.entries(totals).filter(([k,v]) => k != key);

"mamoritai_kono_egao": { // Yaia (護りたい、この笑顔)
    /* snip */
    "type": "critical_up_atk_others",
    "range": range_others,
    "value": { critical: {value: 0.20, attackRatio: 0.20}, normalBuff: 0.05 }
},

// "critical_up_others_20_20" -> "mamorubeshi_sono_egao"
"mamorubeshi_sono_egao": { // Yaia (Holiday) (護るべし、その笑顔)
    /* snip */
    "type": "critical_up_atk_others",
    "range": range_others,
    "value": { critical: {value: 0.20, attackRatio: 0.20}, normalBuff: 0.00 }
},
```

```js
case "critical_up_atk_others":
    if (totals[key].isConsideredInAverage) {
        const {critical, normalBuff} = support.value;
        for (let [name, chara] in support.range(totals, key)) {
            chara["normalOtherCriticalBuff"].push(critical);
            chara["normalBuff"] += normalBuff;
        }
    }
    continue;
```

two improvements
- [ ] pack support specific parameters into "value" field
  - no need to repeat field names in support logic side.
- [ ] set support.range filtering function
  - we have now many clone range loop code,
    we can reuse the filtering logic.


----
### "range" filtering idea

- __all__ ... no need filter
  - const range_all = (totals, key) => totals;
- __own__ ... return only self
  - const range_own = (totals, key) => [totals[key]];
- __others__
  - const range_others = (totals, key) => Object.entries(totals).filter(([k,v]) => k != key);
- element, favorite weapons ... a bit more complex, they can be generic function

```js
const range_element = (element) =>
    (totals, key) => Object.entries(totals, key).filter(([name, chara]) => chara.element == element);

// usage, in support consts: e.g. for light element allies
    "range": range_element("light"),
```

**Comment by h-yasha** [comment]
>     * I could not find info about C.A (ability? or fire heles?)

Ougi buff effect is in the [ougi itself](https://gbf.wiki/Heles_(Wind)). (same applies for aglovale.

>   * 真龍 ... translation (pronounce) for skill id,
>     * [ ]  matatsu -> "shinryu" (but a bit confuse like 神龍 also shinryu/shenlong)
>       matatsu is unusual. but ... I don't know if they speak the kanji in game, Heles fate story etc.

(honestly, i just used google.) I'll change it.

**Comment by kei-gbf** [comment]
> Ougi buff effect is in the ougi itself. (same applies for aglovale.

the 3rd skill ?

- Royal Litany (skill3)
  - ATK is boosted for foes in Overdrive 
    30% for normal attacks; __20% for charge attacks__
- True-Dragon Bond (support1)
  - 30% boost to Heles's ATK and 25% boost to dodge rate when affected by Wind ATK Up

I could not find aglovale 's info about charge attack up too.
it's like Europe's element buff boost, just for own.

- [x] Checked: element buff boost does not stack, max amount is used.

**Comment by kagekiyo7** [comment]
@kei-gbf 
横からすみません、奥義効果のことかと思われます
image

**Comment by kei-gbf** [comment]
I see, ougi buff. then they are not support skill.

- Heles (Wind) ougi buff
  - Massive Wind damage to a foe. (20% boost C.A. specs when Heles is affected by Wind ATK Up) Gain 30% Wind ATK Up
- Agloval ougi buff
  - Massive Water damage to a foe. (20% boost to C.A. specs when affected by Water ATK Up.)

----
- shinryu_to_no_kizuna /* FALLTHROUGH */
- element_buff_boost_own_30_ca_specs_20 /* FALLTHROUGH */
- element_buff_boost

- [ ] shinryu_to_no_kizuna should not fallthrough to element_buff_boost
- [ ] "_ca_specs_20" should be ougi buff? (not implement as support skill)
  - there are ougi buff implemented as support
    but not suit, about include ougi turn or buff available after the ougi ...

**Comment by kei-gbf** [comment]
Proposal for the support logic structure.

```js
switch (support.type) {
  /* snip */
  case "shinryu_to_no_kizuna":
    // do support stuff only
    break;  // <-- NOTICE: not continue;
  case "element_buff_boost_own_30_ca_specs_20":
    /* FALLTHROUGH */
  case "element_buff_boost":
    /* snip */
    break;  // <-- NOTICE: not continue;
}

// Charge attack effect for Heles(Wind) and Agloval
if (support.type === "shinryu_to_no_kizuna"
     || support.type === "element_buff_boost_own_30_ca_specs_20") {
  // when element atk  buff then ca_specs_20
}
```

**Comment by h-yasha** [comment]
> ## Yaia and Yaia (Holiday)
> * skill is similar but name has gap: mamoritai_kono_egao, critical_up_others_20_20

Looking at the whole support abilities names, they are really consistent. I'll be going through them all and also _sorting_ them.

> * [ ]  when Yaia is a main ally. ... how to check this?

currently motocal uses `isConsideredInAverage`, i guess? otherwise, would need to account for indexing in `chara.js`

**Comment by kei-gbf** [comment]
@h-yasha 
sorting ... please do not this time, I will not test all cases.
when missing item by widely changes  but I can't notice that in diff. now it's ok just for new items.
we can have the refactoring topic if need, but another PR.

isConsideredInAverage 
I remember some skill does not care this when sub member or main battle member.
for example, normalSupportKonshin recently added. so we can skip this issue.
mark as TODO and fix with another support together.

**Comment by kei-gbf** [comment]
@h-yasha 

I try to read code and review first, and I will collect change request list later. (or PR if need)
code update while in review sometime add extra tasks, this PR has many topics so it take a time.
so no need to change/fix anything yet (except small fix which not effect to logic)

**Comment by h-yasha** [comment]
@kei-gbf alright, will restrict changes to "wrong"/"better" stuff where it has a significant impact (as in it either simply does not work/etc) only. 
I'll leave the names for now, and before merging I'll change them as appropriate (or when is actually necessary).
(I were actually going to wait up till you "finish" reviewing the whole thing, or have something to do first...)

**Comment by kei-gbf** [comment]
- [ ] Clarisse (Valentine)  isConsideredInAverage: off does not work.
- [ ] Separate support ID for Geisenborger, Wulf and Renie, and [Predator](https://gbf.wiki/Predator)
  - [ ] ougiGageBuff -35%: Geisenborger
  - [ ] ougiGageBuff -35% + TASupport  up: Wulf and Renie,  Predator
    Because, (in future) we want to display DASupport, TASupport
     it's listed in TODO #246 (summary in the top comment)

Currently, some of DA/TA support is hard coded in charaData.json (by python converter script)
no need to implement about the TASupport now, we can do that later.
But it's an important to separate ID now, Save data will store the support ID name.
(backward compatibility issue if we change it later)

**Comment by kei-gbf** [comment]
@h-yasha 
Some of my suggestion are just coding topics, we can skip in this PR. (low priority)
I will send PR for those coding idea. but will not implement them all within this PR.

----
## CriticalDamageLimit (effective)

- [ ] before think the translation ...
  - [ ] I doubt is it necessary to add the field?

the new critical limit field replace current damageLimit in main damage logic code
calcBasedOneSummon() 
This mean the change will effect to all other damage calculation.
the range of change risk is wide, and test range in review too.

- [ ] support can just add to damage limit and ougi limit directly ?

----
## additionalDamage

```js
//additionalDamage based on attacks per turn (sturm support ability-like)
additionalDamage += taRate * totals[key]["additionalDamageTA"]; // additionalDamage On Triple Attack
additionalDamage += (1.0 - taRate) * daRate * totals[key]["additionalDamageDA"]; // additionalDamage On Double Attack
additionalDamage += (1.0 - taRate) * (1.0 - daRate) * totals[key]["additionalDamageSA"]; // additionalDamage On Single Attack
```

I understand they should be in calcBasedOneSummon()
because it required DA/TA rate to calc the damage.

optional topic is, the most of character does not use the additional damages
but calc the default case for all chara.

```js
// value: [0.0, 0.0, 0.15] // in global_const.js
// totals[key]["additionalDamageXA"] = support.value; // XXX: in eachSupport

if (isArray(totals[key]["additionalDamageXA"])) { // and length 3
  let [saDamage, daDamage, taDamage] = totals[key]["additionalDamageXA"];
  /* snip */
}
```
any ways is ok, if the additional damage can be optional case.
(XXX: note in ` = support.value`  if really need the stack then assign sum of two array)

- [x] Check save data does not contains those additionalSA/DA/TA fields
  - no need to worry save data backward compatibility. (about those fields)

**Comment by kei-gbf** [comment]
- [ ] aegisUP where it's used?
- [ ] "fumetsu_no_mikiri" and "tousou_no_chishio" takes `remainHP` then
  - [ ] need to check haisui Graph (and Damage simulator?)
- [ ] case "element_buff_boost":
  - many if/else branches, I think refactoring this code first
    can reduce test costs. (no need to check a lot IF cases)
  - [ ] support.range == "all" && !totals[key].isConsideredInAverage missing buff check
    - [ ] solution: element buff check can be top of those all if/else
  - [ ] number of indent before "continue" (minor coding style fix)

with range filtering idea above, (not completed code)
- [ ] write the main logic code only once
- [ ] filtering function can take "element", "all", "own"  etc. they are re-usable.
  - filter function can be tested, and no need to repeat re-test about filtering
    - hard coded filtering in each support logic, has this cost.

```js
if (totals[key]["elementBuff"] > 0 || buff["element"] > 0) {
    const range_filter = (totals[key].isConsideredInAverage) ? range_own : support.range;
    for (let [name, chara] of Object.entries(totals).filter(support.range, key)) { 
        chara["elementBuffBoostBuff"] = Math.max(support.value, chara.["elementBuffBoostBuff"]);
    }
}
```
(we can optimize more for isConsideredInAverage, I did not think isConsideredInAverage at the first)

**Comment by kei-gbf** [comment]
Unit tests for the support.range filtering idea https://codepen.io/anon/pen/VJydaZ?editors=0011

- I will NOT replace all support.range
  - no touch legacy code, this is not the wide refactoring topic)
- I will try implement "element_buff_boost" with this range filtering
  - Merit: this can reduce review/test costs by simplify code

**Comment by kei-gbf** [comment]
## element_buff_boost

- shinryu_to_no_kizuna (Heles (Wind))
  - [ ] Separate the ougi effect
- element_buff_boost_own_30_ca_specs_20 (Agloval)
  - [ ] Separate the ougi effect
- element_buff_boost_damageUP_own_10 (Olivia)
  - [x] no check enemy element in support logic
    - [x] ok, "charaDamageUP" can assume enemy element "light" since Olivia is "dark"

----
### support.when field

`if (totals[key]["elementBuff"] > 0 || buff["element"] > 0)`

To reuse the code, support.when field (proposal)

```js
const element_buff = (totals, key, buff) =>
    (totals[key]["elementBuff"] > 0 || buff["element"] > 0);
```

```js
shinryu_to_no_kizuna: // unique name, can be character specific
  type: normalBuff
  when: element_buff
  range: own
  value: 0.30

damageUP_own_10: // common name, can assume parameter-lize use case
  type: damageUP
  when: element_buff
  range: own
  value: 0.10

element_buff_boost_own_30:
  type: element_buff_boost
  when: element_buff
  range: own
  value: 0.30
```

```js
for (let [name, chara] of support.range(totals, key)) {
  if (support.when(totals, key, buff)) {
    // implement the support logic
  }
}
```

**Comment by kei-gbf** [comment]
## Change requests

- [ ] Yaia / Yaia (Holiday) ... can be same/similar support name/type
- [ ] Clarisse (Valentine) ... need isConsideredInAverage check
- [ ] Lancelot and Vane: where is aegisUP implementation
- [ ] case "no_normal_attack": missing continue in switch
- [ ] element_buff_boost
  - [ ] Separate ougi effects
    - [ ] Heles (Wind)
    - [ ] Agloval
    - [ ] at least, need explain it's by ougi effect, if support will contain this.
- [ ] CriticalDamageLimit (effective)
  - [ ] translation (ja)  ... I don't know what should be

I will make PR the "range" filtering implementation
that will apply to:

- [ ] element_buff_boost
- [ ] critical_cap_up

not sure about "when" filtering, yet. it's just stage: idea now(TODO)

## Review / Test

- [ ] RemainHP ... check haisui Graph
  - [ ] Beatrix (Themed)
  - [ ] Ayer
  - [ ] Sara
- [ ] change calcBasedOneSummon (this may have side effect widely)
  - [ ] AdditionalDamageXA
    - [ ] Levin Sisters
    - [ ] Strum
  - [ ] Critical Damage Cap UP (criticalDamageLimit)
    - [ ] Eugen (Grand)
    - [ ] Silva (Light)

**Comment by kei-gbf** [comment]
- [ ] Yaia / Yaia (Holiday) ... can be same/similar support name/type
- [ ] Clarisse (Valentine) ... need isConsideredInAverage check
- [ ] AdditionalDamageXA improve
- [ ] Separate support ID for Geisenborger, Wulf and Renie, and Predator

I will do those next, as explained in comments.

**Comment by kei-gbf** [comment]
I had extended the default processing.
(not PR yet, it's now local works)

```js
// Processing in case of simple buff system

// FIXME: restrict filtering range function lookup
//   currently support "all", "own", "others", "Djeeta"
//   not work well with, range: "element" etc .. use range function

let range_filter = range[support.range] || support.range;
for (let [name, chara] of range_filter(totals, key)) {
    // if (support.when && !support.when(chara, buff)) continue;
    switch (support.assign || "add") {
        case "push":
            chara[support.type].push(support.value);
            break;
        case "max":
            chara[support.type] = Math.max(support.value, chara[support.type]);
            break;
        case "add":
            chara[support.type] += support.value;
            break;
    }
}
```

```js
"critical_up_own_40_50": {
    "name": "クリティカル確率UP(発動率40%, 倍率50%)(キャル)",
    "type": "criticalBuff",
    "assign": "push",
    "range": "own",
    "value": {value: 0.40, attackRatio: 0.50}
},
```

then I could remove the critical processing code in each Support.

TODO: Implement composite pattern can improve for composite skill which has more than two effects.

----
Too much extra topics now, I will just memo (not going deep into this)
(I did not implement below, yet. but it's simple and easy to do)

- eachSupport() generator can hook to expand composite support effects
  - for example, if the support was "composite" item then

```js
// extend eachSupport() return each composite support
if (supportAbilities[chara[key]].type === "composite") {
    for (let support of supportAbilities[chara[key]].value) {
        yield supportAbilities[support.name] || support;
    }
    continue;
}
```

Default buff system can process those composite items as single buff.
This change make support skill more re-usable. (without fallthrough approach)
```js
"knightmare_frame": {
    "name": "HP15%UP&DEF10%UP&奥義ゲージ上昇量25%DOWN(ルルーシュ・ランペルージ, 枢木スザク, 紅月カレン)",
    "type": "composite",
    "value": [
        {type: "HPDebuff", range: "own", value: 0.15},
        {type: "ougiGageBuff", range: "own", value: -0.25},
        // or {name: "ougi_gage_down_25"} for reuse
    ]
},
```

It's known as Composite pattern in OOP(Object Oriented Programming)

**Comment by kei-gbf** [comment]
my PR had a bug, the composite support had a limitation,
that could not process composite type in the composite.
I will fix that later, no issues for this PR.

**Comment by h-yasha** [comment]
- [x] Fix overwritten code through merge conflicts:
    - [x] aegisUP. (lancelot and vane)
- [ ] Create a function to re-treat support abilities, specifically HP based ones. (Enmity Graph/Damage Simulator).
    - [ ] also merge recalcCharaHaisui, and recalcNormalSupportKonshin with it. 
     - rather than hardcoding, a better way to filter them?
- [ ] Clarisse (Valentine): check isConsideredInAverage

Note: Wulf/etc passive TA rate is high than 100%.

**Comment by kei-gbf** [comment]
- [x] Clarisse (Valentine): check isConsideredInAverage

> Wulf/etc passive TA rate is high than 100%.

OK, they are now 1000 internally, just display 100%

>  Create a function to re-treat support abilities, specifically HP based ones. (Enmity Graph/Damage Simulator).
 also merge recalcCharaHaisui, and recalcNormalSupportKonshin with it.
rather than hardcoding, a better way to filter them?

Yes, it's good idea, if no repeat same/similar clone code, make maintenance easy.
and also review once, no need to check three-places.

**Comment by kei-gbf** [comment]
- [x] confirm: Olivia 's charaDamageUP it stack?
  - not sure about stack within charaDamageUP, at least no stack with tenshi is ok
    I understood now why charaDamageUP field was used. in main damage logic:
    `damageUP += Math.max(totals[key]["tenshiDamageUP"], totals[key]["charaDamageUP"]);`
  - [x] how to check in result (display in skill result)
    - displayed in Damage UP, when enemy is light and element buff ... I was missing the condition.
- [ ] where display AdditionalDamageXA amount (display in skill result)

I will display AdditionalDamageXA, like critical field:

| adddional damage | SA | DA | TA |
|-------------------------|----|----|----|
| amount | 0 | 0 | 15% |

**Comment by h-yasha** [comment]
_Update regarding progress: there's not any._
_(i don't have access to the code right now)_

>- [ ] Create a function to re-treat support abilities, specifically HP based ones. (Enmity Graph/Damage Simulator).
> - [ ] also merge recalcCharaHaisui, and recalcNormalSupportKonshin with it.
> rather than hardcoding, a better way to filter them?
> 

- It's difficult would need to change [hasui graph/damage simulator calc functions] to re calculate a lot of stuff which are being calculated in [calcBasedOneSummon] with more or less duplicated code (which is undesirable), and would make this PR changes a lot of things.
- [ ] As such, I'll try to remove Ayer and Beatrix (Themed) Support abilities (comment out to be implemented again when appropriate changes are made) soon.

**Comment by h-yasha** [comment]
**BUG:** Djeeta's Extended Mastery DMG Cap is not being handled properly. (before the PR and after the PR.)

**Comment by kei-gbf** [comment]
> It's difficult would need to change [hasui graph/damage simulator calc functions] to re calculate a lot of stuff which are being calculated in [calcBasedOneSummon] with more or less duplicated code (which is undesirable), and would make this PR changes a lot of things.

I see, I recognize it's a structural problem of program design
(on this design, it's requires three similar changes) so rest task in this PR is
- [ ] list up those todo tasks and update in the PR's comment.

----
> much comment out code

you can just remove those code. Instead of comment out
we can handle them with git, restore from git when needed again.
make a patch file of the commit, or keep the branch copy on remote repo etc.

for more detail, it's known issue to commit comment out code in collaborate repo.
there are several reasons and Q&A. https://kentcdodds.com/blog/please-dont-commit-commented-out-code

----
as replacement of remove those comment out code,
I suggest leave the simple comment.
python code is the entry point of implementing new support ability.

```python
# Not implemented: see #259 for details
# supportAbilist["tousou_no_chishio"] = {
#     u"闘争の血潮"
# }
```
- [ ] comment on u"不滅の見切り" as well.
- [ ] remove those comment out code in js files. it's easy to restore.

When other developers want to implement the same feature,
at least they can find here from the comment.

and *important* update the PR comment (the first comment of this page)
they will find easily the information summary.

----
or other choice
- implement this as uncompleted feature (with explain it has issue on graph/simulator)

```python
supportAbilist["tousou_no_chishio"] = {
    # u"闘争の血潮"
}
```
this will show in support list but character does not set by default? isn't it.
and make a report issue to keep this as known issue. (or TODO comment in source)

Merit of this is. translation etc were reviewed once.
when implemented the feature again, some of code are no need to re-review.

Demerit is Users may confuse as it's implemented,
the most of the case when affected by remain HP, they may want to see the graph.
I don't know about Damage simulator.

Other trade off of enable  `supportAbilist["tousou_no_chishio"]` entry is:
- support ability ID will be stored in save data.
   after merge it to master, we can't change it easily (for backward compatibility reason)

**Comment by kei-gbf** [comment]
Tasks for this PR
- [ ] solve conflict
- [ ] remove commented code
  please do this after solve the conflict in separate commit, 
  then you can restore the changes by revert the commit.

**Pull request merged**
