### PR TITLE
Fix typo skill amount label type

### PR DESCRIPTION
**Pull request by Marco3jp**
- There was typo skill amount label. ( I'm selecting to see the letters. )
Screenshot_2021-01-05_19-24-05

- I fix it.
  - succes -> success

### CODE REVIEW

**Review by kagekiyo7 — APPROVED** [review]
LGTM!

**Comment by Marco3jp** [comment]
@kagekiyo7  Umm...It seems to be [ci](https://travis-ci.org/github/MotocalDevelopers/motocal/builds/752972119) passed. Can you check for GitHub and CI issues?

**Comment by kagekiyo7** [comment]
I'm sorry, I don't know.
However, test has passed in travis-ci.
https://travis-ci.org/github/MotocalDevelopers/motocal/pull_requests

**Comment by Marco3jp** [comment]
There was a post on this issue on the Travis CI forum.
https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

Also, "travis-ci.org" will be closed in the future, so you may need to migrate to "travis-ci.com". (I don't know the details. automatically?)
However, it seems that the same problem may still occur despite the measures and migration.
If there is no special reason, I think it is also possible to migrate tests of travis.yml to GitHub Actions.

I'm sorry not to help. For reference, here is the GitHub Actions configuration that I created before.
https://github.com/Marco3jp/paradise-lost/blob/master/.github/workflows/cd.yaml

**Pull request merged**
