### PR TITLE
Recent patches, normal critical change

### PR DESCRIPTION
**Pull request by Groovman**
Recent added characters, uncaps, weapons added to the game. Normal critical calculation change. Fixes for ougi and turn calculation.

----
- [x] Fix Ougi Damage Calc a98e426
- [x] Added missing dependencies by OrkunKocyigit de7e87b
- [x] Add Main Character and Party C.A Damage Up by OrkunKocyigit 82348ab
- [x] Sorted Individual Buff order 9585bcf
- [x] Fix minimum turn becoming infinite 784e112
- [x] Merge remote-tracking branch 'origin/master'  … e590699
- [x] Removed wrong merges 37ac41c
- [x] Merge remote-tracking branch 'origin/master'  … 019acd3
- [x] Gladi weapon skills 6a347f5
- [x] Class and Weapons for Patch 2019-05-27  … 52fce0e
- [x] New normal critical calculation (LB and other critical calculation un… f212535

### CODE REVIEW

**Comment by kei-gbf** [comment]
```md
----
- [x] Fix Ougi Damage Calc a98e426
- [ ] Added missing dependencies by OrkunKocyigit de7e87b
- [ ] Add Main Character and Party C.A Damage Up by OrkunKocyigit 82348ab
- [ ] Sorted Individual Buff order 9585bcf
- [x] Fix minimum turn becoming infinite 784e112
- [ ] Merge remote-tracking branch 'origin/master'  … e590699
- [ ] Removed wrong merges 37ac41c
- [ ] Merge remote-tracking branch 'origin/master'  … 019acd3
- [ ] Gladi weapon skills 6a347f5
- [ ] Class and Weapons for Patch 2019-05-27  … 52fce0e
- [ ] New normal critical calculation (LB and other critical calculation un… f212535
```

I can review the two related to #212

@Groovman 
Can you paste this list to the first comment, If this PR review take long time.
I'd like to see the progress status. it's ok if others can review this quickly.

----

> minimum turn becoming infinite

```jsx
// Normal attack * n times
var expectedCycleDamage = expectedTurn * expectedAttack * damage;
// Ougi + chain burst (buff ["chainNumber"] is 1 or more so division OK)
expectedCycleDamage += ougiDamage + chainBurst / buff["chainNumber"];
var expectedCycleDamagePerTurn = expectedCycleDamage / (expectedTurn + 1.0);
```

Ougi won't happen for the Infinity case ?
Can this solve by skipping ougi damage, instead of setting minimum turns?

```jsx
if (Math.isFinite(expectedTurn)) {
    ...
} else {
    var expectedCycleDamagePerTurn = expectedAttack * damage;
}
```

I am not sure which Infinity check for this context.
- `!Math.isFinite(expectedTurn)`
- `Math.abs(expectedTurn) === Infinity`
- `expectedTurn === Number.POSITIVE_INFINITY`

Math.min check may not treat negative infinity case. (I don't know it happen or not)

Other possibility division by zero or infinity ... when expectedTurn was negative number.
so instead of checking expectedTurn is Infinity, ougi gage up is 0 or negative also can check this.

**Comment by h-yasha** [comment]
> minimum turn becoming infinite

How about just checking `expectedOugiGage` if is 0 then flag `expectedTurn` _(I have it as 0 as a workaround)_. and completely ignoring `minimumTurn`
and check later for (not) the flag/is 0 and add the ougi damage and chainburst
```
var expectedCycleDamage = expectedTurn * expectedAttack * damage;
if (expectedTurn != 0) {
    expectedCycleDamage += totals[key]["ougiPerTurn"] * ougiDamage + chainBurst / buff["chainNumber"];
}
```

**Comment by kei-gbf** [comment]
@h-yasha 
I do not know what formula make expectedTurn is 0
and totals[key]["ougiPerTurn"]

I agree calc expectedCycleDamage = expectedAttack * damage; first is better.

**Comment by kei-gbf** [comment]
- [x] New normal critical calculation (LB and other critical calculation un… f212535
  - [x] test Ecke Sachs  x6 with 120x120 primal summons aura ... Probability: 100%

normal-crit

**Comment by h-yasha** [comment]
_oh i missed up my copy paste, `totals[key]["ougiPerTurn"]` shouldn't be there... just some 'hack stuff'..._
_i could not reference expectedOugiGage since there were changes in the recent PRs._

minimumTurn and expectedTurn should only be infinite when:
`var expectedOugiGage = buff["ougiGage"] + totals[key]["ougiGageBuff"] - totals[key]["ougiDebuff"];`
is 0. (the other line will only multiply it. shouldn't really matter)
then:
`var expectedTurn = expectedOugiGage != 0 ? OugiGage / expectedOugiGage > minimumTurn ? OugiGage / expectedOugiGage : minimumTurn : 0;`

**Comment by kei-gbf** [comment]
## Weapons

- [x] fix attack/hp (lv100) 
  - a lot weapons updated, from wiki? TODO: I will make a list and validation script.
- add new weapon data
  - [x] John Doe [Element Changed]
  - [x] True Grit
  - [x] Spymur's Clause
  - [x] [4★] Spymur's Clause

----

## Characters

- new
  - [x] Baal
  - [x] Aster (wind Aster was renamed to Event version)
- uncap
  - [x] Shao

NOTE: I just check those data added, not check the status values etc

----
## arm data

- [x] fix arm_data_converter.py magnaKatsumokuS water
- [x] add new skill Power Bomb (earth) strengthL
- [x] fix broken letter at dagger of cosmos 

----
## global_logic.js

- normal critical change
  - [x] just watch normal critical code similar to magna critical
  - [x] magna critical statement move to next of normal critical

----
@Groovman 

This is kind of main update, users should notice new characters/weapons/job
Can we add message to notice.js

```json
    "notice-20171011-1": {
        "en": "11/10/2017: Added new weapons and characters.",
        "ja": "2017/10/11: 武器とキャラ追加.",
        "zh": "2017/09/07: 增加新武器和新角色。",
    },
```

I found this can be the template message for weapon/character update.
If others want to add something additional info, they can request in PR review stage.

- [ ] add translation key (date and incremental number) to notice.js
- [ ] add message text in translate.js

**Comment by kei-gbf** [comment]
@h-yasha 
I am new on this Ougi gage context.
what I understand now is

`var expectedCycleDamagePerTurn = expectedCycleDamage / (expectedTurn + 1.0);`

when expectedTurn was Infinity, the result became NaN.
showing the result turn "Infinity T" is Ok, or should be "0 T" ?
I have no idea about what `expectedTurn` number should be displayed.

Anyway, avoid add ougi for the ougi gage 0% case
can avoid the division by infinity turn.

----
eslint may not allow the nested ternary operator, just coding style.
```diff
- var expectedTurn = expectedOugiGage != 0 ? OugiGage / expectedOugiGage > minimumTurn ? OugiGage / expectedOugiGage : minimumTurn : 0;
+ var expectedTurn = expectedOugiGage <= 0 ? 0 : Math.max(OugiGage / expectedOugiGage, minimumTurn);
```

**Comment by Groovman** [comment]
@kei-gbf 
notice added

**Comment by Groovman** [comment]
The tooltip fits both limit and dmg up because both are used for ougi calc.

**Comment by kei-gbf** [comment]
@Groovman 
I see, same tool tip used.

the translation key had ambiguous info,
the key is "Ougi Damage Limit Up explanation" but translation explain Ougi damage.
and the tool tip used for ougi damage and ougi damage limit.

```json
"奥義ダメージ上限アップ説明": {
    "en": "It is used to calc the Ougi damage.",
    "ja": "奥義ダメージの算出に使用されます。",
    "zh": "奥义伤害的计算中有用到。",
},
```

I look another buff fields, personal buff did not have the tool tips.
other field explained about stars.
this is another issue, need more review around tooltip and translation.

- [x] Sorted Individual Buff order

**Comment by kei-gbf** [comment]
- [ ] checking weapons status updated
  Not completed yet, I just put this as base code for scrape wiki data.
  https://gist.github.com/kei-gbf/f0cb75c138f945de8e54048faf2d1875
- [ ] minimum turn becoming infinite
  I sent PR. This was before h-yasha gave an idea. calc ougi gage 0% case first is better.
  This commit just show there are two places had this formula.
  https://github.com/Groovman/motocal/pull/8/commits/c32cc9e08aac2f05f6a8c066ca15866b1a699402
- [ ] Added missing dependencies by OrkunKocyigit de7e87b

----
de7e87b (package.json の更新) は、実際に運用してる環境でテスト・確認して貰った方がいいのかな？
ライブラリの更新が必要になります。

NOTE: for server admin, de7e87b change requires library update.

**Comment by kei-gbf** [comment]
- [x] fix "ja" had broken letters
  - [x] Gauntlet of Uriel (SR) 
  - [x] タイラントボウ (no "en" translation)

----
| name | gbf.wiki | armData.json |
|---|---:|---:|
| Skofnung [Element Changed] | 209/2405 | 209/2405 |
| Aschallon [Element Changed] | 205/2425 | 205/2425 |
| Proximo [Element Changed] | 205/2410 | 205/2410 |
| Ipetam [Element Changed] | 226/2320 | 226/2320 |
| Faust [Element Changed] | 231/2295 | 231/2295 |
| Misericorde [Element Changed] | 229/2305 | 229/2305 |
| Romulus Spear [Element Changed] | 248/2210 | 248/2210 |
| Avenger [Element Changed] | 182/2540 | 182/2540 |
| Nirvana [Element Changed] | 276/2070 | 276/2070 |
| Keraunos [Element Changed] | 232/2200 | 232/2200 |
| Kapilavastu [Element Changed] | 278/2060 | 278/2060 |
| Oliver [Element Changed] | 171/2595 | 171/2595 |
| Nebuchad [Element Changed] | 169/2605 | 169/2605 |
| Hellion Gauntlet [Element Changed] | 237/2265 | 237/2265 |
| Rosenborgen [Element Changed] | 219/2410 | 219/2410 |
| Langeleik [Element Changed] | 233/2120 | 233/2120 |
| Murakumo [Element Changed] | 181/2565 | 181/2565 |
| Muramasa [Element Changed] | 177/2585 | 177/2585 |

----
| name | gbf.wiki | armData.json |
|---|---:|---:|
| Guardian's Xiphos [Element Changed] | 209/2405 | 209/2405 |
| Ridill [Element Changed] | 205/2425 | 205/2425 |
| Wasserspeier [Element Changed] | 205/2410 | 205/2410 |
| Original Sin [Element Changed] | 226/2320 | 226/2320 |
| Psycho Syringe [Element Changed] | 231/2295 | 229/2276 |
| Helmwige [Element Changed] | 248/2210 | 248/2210 |
| Berserker's Barrage [Element Changed] | 182/2540 | 182/2540 |
| Hallowed Pilgrimage [Element Changed] | 276/2070 | 276/2420 |
| Demonic Longstaff [Element Changed] | 232/2200 | 231/2105 |
| Lunatic Broom [Element Changed] | 278/2060 | 278/2060 |
| The Storyteller [Element Changed] | 171/2595 | 171/2595 |
| John Doe [Element Changed] | 169/2605 | 169/2605 |
| Championship Belt [Element Changed] | 237/2265 | 237/2265 |
| Maverick [Element Changed] | 219/2410 | 219/2410 |
| Chanteuse Angelique [Element Changed] | 233/2120 | 233/2120 |
| Unsigned Kaneshige [Element Changed] | 181/2565 | 181/2565 |
| Tetrastreamer [Element Changed] | 177/2585 | 177/2585 |

This is script generated report. test only class weapons Element Changed.
NOTE: EX2 class weapon gbf.wiki page did not have lv100 field
so this refer to Rebirth weapon's status.

@Groovman 

Can you check these three lv100 hp/attack fields
- [ ] Psycho Syringe [Element Changed]
- [ ] Hallowed Pilgrimage [Element Changed]
- [ ] Demonic Longstaff [Element Changed]

Now I scrape data from gbf.wiki, I could not find data in gbf-wiki.com
https://gist.github.com/kei-gbf/78d653a5f7ec7d2e02ebcb7401b60e2c

**Comment by kei-gbf** [comment]
> minimum turn becoming infinite

@h-yasha 
I already had sent the PR before your comment,
the patch fix NaN case at least
but it's a bit different expectedTurn display 0 T or Infinity T.
I am not sure about this, tell us in #212 if this is still issue.

**Pull request merged**
