### PR TITLE
Add support for Math.ceil of  expected ougi gage

### PR DESCRIPTION
**Pull request by kagekiyo7**
test:
TA 100%, Charge Bar Buff 50% 
→ 37.0x1.5=55.5% → expected ougi gage(Charge Bar Rise per Turn) 56%
image

### CODE REVIEW

**Comment by OrkunKocyigit** [comment]
I have issue understanding this formula as a general.
If I have character with %100 TA and 0% buff then in game I would gain 30% charge bar every turn right? Where does the 37% coming from?

**Comment by kagekiyo7** [comment]
> I have issue understanding this formula as a general.

It's bonus.

> Double Attacks give a bonus of 2% and Triple Attacks give a bonus of 7%. A Single Attack therefore generates 10% charge bar, a Double Attack 22% and a Triple Attack 37%. This bonus is affected by Charge Bar speed up buffs.
> https://gbf.wiki/Charge_Attack

**Comment by OrkunKocyigit** [comment]
LOL I never realized past 2 years I have been playing. I'll try check this PR later.

**Comment by OrkunKocyigit** [comment]
I tried to simply formula via wolfram but it says it is as good as gets. Tests look fine. Thank you for your work

**Comment by kagekiyo7** [comment]
Thank you for the review. I would like this when there is time.
#293

**Pull request merged**
