### PR TITLE
Recent uncaps

### PR DESCRIPTION
**Pull request by Groovman**
- [x] Delta Quartz
- [x] Mettle 
- [x] Ouroboros Treat
- [x] Meteora 
- [x] Deirdre's Claws

| gamewith | gbf.wiki |
|-|-|
| [デルタ・クォーツ](https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/71766) | [Delta Quartz](https://gbf.wiki/Delta_Quartz) |
| [ブラビューラ](https://gbf-wiki.com/index.php?%C9%F0%B4%EF%2F%A5%D6%A5%E9%A5%D3%A5%E5%A1%BC%A5%E9%20%28SSR%29) (gbf-wiki) | [Mettle](https://gbf.wiki/Mettle) |
| [トリート・ウロボロス](https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/71992) | [Ouroboros Treat](https://gbf.wiki/Ouroboros_Treat) |
| [メテオラ](https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/72048) | [Meteora](https://gbf.wiki/Meteora) |
| [フェイトルーラー](https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/90552) | [Ruler of Fate](https://gbf.wiki/Ruler_of_Fate) |
| [ディアドリッククロー](https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/72092) | [Deirdre's Claws](https://gbf.wiki/Deirdre's_Claws) |

### CODE REVIEW

**Comment by kei-gbf** [comment]
----
please add this checklist for progress status to PR comment
```md
- [ ] Delta Quartz
- [ ] Mettle 
- [ ] Ouroboros Treat
- [ ] Meteora 
- [ ] Deirdre's Claws
```

----
and also this (converted from commit log + add English wiki link)
it's useful to be sticked on the top comment.

```md
| gamewith | gbf.wiki |
|-|-|
| [デルタ・クォーツ](https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/71766) | [Delta Quartz](https://gbf.wiki/Delta_Quartz) |
| [ブラビューラ](https://gbf-wiki.com/index.php?%C9%F0%B4%EF%2F%A5%D6%A5%E9%A5%D3%A5%E5%A1%BC%A5%E9%20%28SSR%29) (gbf-wiki) | [Mettle](https://gbf.wiki/Mettle) |
| [トリート・ウロボロス](https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/71992) | [Ouroboros Treat](https://gbf.wiki/Ouroboros_Treat) |
| [メテオラ](https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/72048) | [Meteora](https://gbf.wiki/Meteora) |
| [フェイトルーラー](https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/90552) | [Ruler of Fate](https://gbf.wiki/Ruler_of_Fate) |
| [ディアドリッククロー](https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/72092) | [Deirdre's Claws](https://gbf.wiki/Deirdre's_Claws) | 
```

preview:

| gamewith | gbf.wiki |
|-|-|
| [デルタ・クォーツ](https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/71766) | [Delta Quartz](https://gbf.wiki/Delta_Quartz) |
| [ブラビューラ](https://gbf-wiki.com/index.php?%C9%F0%B4%EF%2F%A5%D6%A5%E9%A5%D3%A5%E5%A1%BC%A5%E9%20%28SSR%29) (gbf-wiki) | [Mettle](https://gbf.wiki/Mettle) |
| [トリート・ウロボロス](https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/71992) | [Ouroboros Treat](https://gbf.wiki/Ouroboros_Treat) |
| [メテオラ](https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/72048) | [Meteora](https://gbf.wiki/Meteora) |
| [フェイトルーラー](https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/90552) | [Ruler of Fate](https://gbf.wiki/Ruler_of_Fate) |
| [ディアドリッククロー](https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/72092) | [Deirdre's Claws](https://gbf.wiki/Deirdre's_Claws) |

**Comment by kei-gbf** [comment]
I forgot to add that [4★] to list names

- [ ] Delta Quartz lv150 HP, site had wrong data ?
  - gamewith: 425 ... look like a clone of min ATK
  - gbf.wiki: 260
- gbf.wiki missing some of lv150 status, manually checked
  - [x] Ouroboros Treat
  - [x] Meteora
  - [x] Deirdre's Claws
- [x] other status (hp/atk lv1/100/150) ok

it was good practice to know the information source,
we can check other source for validation.
(if check with same source, then can't catch the source mistake)

----

| en | element/type | skill1 | skill2 | skill3 |
|---|---|---|---|---|
| Delta Quartz | fire/dagger | normalSanteL/fire | non/fire | normalHaisuiS/fire
| Mettle | earth/axe | normalL/earth | non/earth | non/earth
| Ouroboros Treat | dark/wand | normalL/dark | non/dark | normalHPS/dark
| Meteora | water/gun | normalL/water | normalHaisuiS/water | non/water
| Ruler of Fate | light/gun | normalL/light | normalHiouS/light | ougiDamageLimitExceedM/light
| Deirdre's Claws | wind/fist | normalHaisuiL/wind | normalCriticalM/wind | non/wind

- [ ] TODO: check skill details
  - [ ] Delta Quartz / normalHaisuiS
  - [x] Mettle / Motocal does not support
  - [ ] Ouroboros Treat / normalHPS
  - [x] Meteora / Motocal does not support
  - [ ] Ruler of Fate / ougiDamageLimitExceedM
  - [ ] Deirdre's Claws / skill2 amount change

----
ステータス確認終わりました。デルタ・クォーツHPのみ要修正
残りスキルの詳細チェック（効果量等）

**Comment by Groovman** [comment]
Updated the Delta Quartz HP, gamewith is mostly the one that had the data first, but most often has errors. gbf-wiki switches up number sometimes or shows outdated data, gbf.wiki is mostly reference for me (but also slowest to update).

**Comment by kei-gbf** [comment]
I was missing to the first list
- [x] Ruler of Fate

review done

**Pull request merged**
