### PR TITLE
Fix ougiRatio of undefined

### PR DESCRIPTION
**Pull request by kagekiyo7**
- [x] Change confirmation method to isNaN
(it can cover undefined, null, NaN)
- [x] Add DEFAULT ougiRatio value in global_const.js

Discussion:
https://github.com/MotocalDevelopers/motocal/pull/305

close #305

### CODE REVIEW

**Comment by kei-gbf** [comment]
- [ ] parseInt ... should be float ?
- [ ] "4.5" is a magic number hard coded in logic, should be declare in const
  - DEFAULT.ougiRatio like a "LIMIT"
    (no need to change another default values in this PR, only ougiRatio now)
- [ ] undefined check
  - [x] `null != undefined` => false
  - [x] `undefined != undefined` => false
  - [ ] `non_number_object != undefined` => true

FYI undefined check 
https://eslint.org/docs/rules/no-undefined
`typeof obj === "undefined"`

but this code could not check "null" case. (it won't happen ?)
then isNaN (not a number) for the number check

- !isNaN
  - !isNaN(undefined) => false
  - !isNaN(null) => false
  - !isNaN(non_number_object) => false
  - !isNaN("10") => true ... it return true even string type that possible to convert to number

`!isNaN(ougiRatio) ? parseFloat(ougiRatio) : DEFAULT.ougiRatio`

- NOTE: we can't `parseFloat(ougiRatio) || DEFAULT.ougiRatio` that ignored ougiRatio: 0 case.
  - it's useful short code works sometime but there was several issues with "0" case.

**Comment by kagekiyo7** [comment]
>parseInt ... should be float ?

>"4.5" is a magic number hard coded in logic, should be declare in const

>but this code could not check "null" case. (it won't happen ?)

done

**Comment by kei-gbf** [comment]
- [ ] summary on PR comment (as history of working log)
  - [ ] `close/fix/resolve #305` can close automatically close 305 when this PR is closed.
  - https://help.github.com/en/articles/closing-issues-using-keywords
- [x] Add "duplicate" label on #305

**Comment by kagekiyo7** [comment]
>summary on PR comment (as history of working log)

done👍

**Comment by kei-gbf** [comment]
I will test following:

- [ ] remove "ougiRatio" field in JSON, and load the save data.
  - [x] #305 approach avoid whiteout but show the skill value NaN.
  - [ ] #307 will show the default value.

**Comment by kagekiyo7** [comment]
🤔
image

**Comment by kei-gbf** [comment]
類似の問題がないか検索してみたけど、
特定の原因は解らずGithubサポートに連絡といった回答がありました。

試しに何か追加でコミットして貰えますか？

空コミットは多分オプションで何か指定しないと無理なので、
支障のなさそうな変更

Commit log: "code formatting"
```diff
- const {LIMIT} = GlobalConst;
- const {DEFAULT} = GlobalConst;
+ const {LIMIT, DEFAULT} = GlobalConst;
```

で、新たにテストをパスした後にステータスが更新されるのを期待してみます。
もし無理そうなら、新規にPR作り直しをお願いします。

----

Anyone know this problem?
repo setting changes ? or something happen unsync status?
I found two were answered contact to github suport.

- [Merge button is disabled after all the checks passed on Github](https://stackoverflow.com/questions/52513569/merge-button-is-disabled-after-all-the-checks-passed-on-github)
- [PR says "Required statuses must pass before merging", but all *have* passed](https://github.community/t5/How-to-use-Git-and-GitHub/PR-says-quot-Required-statuses-must-pass-before-merging-quot-but/td-p/4919)

I 've suggested now is, add new commit to expect update the status checks.
or re-make new PR.

**Comment by Groovman** [comment]
```
const {
     LIMIT,
     DEFAULT
} = GlobalConst;
```
I think it is that comma too much.

**Comment by Groovman** [comment]
Lol, nvm XD

**Comment by kagekiyo7** [comment]
it went well.
thank you :)

**Comment by kei-gbf** [comment]
@Groovman 
> I think it is that comma too much.

Yes, I was going to write that topic, it's extra topic

- [ ] JSON ... disallow trailing commas
- [ ] ES6 ... Babel will transpile
  - ESLINT rule https://eslint.org/docs/rules/comma-dangle
- [ ] Python ... ok

----

e.g. add new item "C"

no comma source
```js
A,
B
```

the changes diff:
```diff
A,
- B
+ B,
+ C,
```

with comma source
```js
A,
B,
```

the changes diff:
```diff
A,
B,
+ C,
```

the change is more compact and clear.

This require comma rule may make confuse for JSON,
and legacy code disallow the trailing commas.

it's topic like
follow legacy rule or improved new style.
this project does not have coding style rule,
we should share the style rules. (it's eslint's job but hard to do with much legacy code)

similar diff by coding style topic about insert_final_newline in #242

**Comment by kei-gbf** [comment]
ah Ok, now I understood, it was like I had asked the problem for the code.
my question was for github "Request status ..." I had written different things in Ja/En.

**Pull request merged**
