### PR TITLE
Implementing Amplified DMG Buff

### PR DESCRIPTION
**Pull request by OrkunKocyigit**
**Scope of Change:**

This PR aims to implement DMG Amplified Buff for Djeeta and Characters to allow calculation for chars such as Summer Sandy and Seox.

**Requirements:**

- DMG Amplified is seraphic buff.
- DMG Amplified stacks additive with current seraphic sources.
- DMG Amplified only effects normal attacks. It does not effect ougis.

image

**Changes included in this PR**
- [ ] Djeeta now has personal seraphic buff under invidual buffs.

image

- [ ] Party buffs now has seraphic buff.

image

- [ ] Characters now has seraphic buff.

image

- [ ] Profile has a tooltip for party seraphic buff explaining what it does.
image

image

- [ ] seraphicBuff has been added to basically every model object in globalLogic.

- [ ] damageUP buff has been split into damageUP (For All) and damageUPWithoutOugi (For Only Ougis)

**Changes NOT included in this PR**
- Different labels for damageUP and damageUPWithoutOugi on skill UI.

### CODE REVIEW

**Comment by kagekiyo7** [comment]
Name "Seraphic Buff" may be confused with Normal Seraphic effect. (Seraphic Weapons etc)

Name improvement plan:
EN - `Boost DMG buff (only one-foe attacks)` or `Amplify DMG`
JP - `与ダメージUPバフ(通常攻撃のみ)`

**Comment by kagekiyo7** [comment]
> damageUP buff has been split into damageUP (For All) and damageUPWithoutOugi (For Only Ougis)

I don't understand why damageUPWithoutOugi is For Only Ougis… (without? only?)
Also I think `damageUPOnlyNormalDamage` are easier to understand than `damageUPWithoutOugi`.

**Comment by OrkunKocyigit** [comment]
@kagekiyo7
Updated to your syntax recommendation.

**Comment by OrkunKocyigit** [comment]
@kagekiyo7
Updated to your syntax recommendation.

**Comment by kagekiyo7** [comment]
I fixed some. 

----

```js
        "en": "DMG for one-foe attacks and counterattacks is amplified",
```
counterattacks? It isn't implemented and I guess you shouldn't write...

---

Can I move field to the bottom? Because it is not used frequently.

**Comment by OrkunKocyigit** [comment]
I moved to bottom of the list and updated translation keys

**Comment by OrkunKocyigit** [comment]
I moved to bottom of the list and updated translation keys

**Comment by OrkunKocyigit** [comment]
I moved to bottom of the list and updated translation keys

**Comment by OrkunKocyigit** [comment]
I moved to bottom of the list and updated translation keys

**Comment by kagekiyo7** [comment]
`"en": "DMG and DMG CAP for one-foe attacks are amplified. EX, Kumbhira, Seox 2nd Skill",`

OK, but I don't recommend displaying the adding description, since they are personal buff and displaying in party buff field.

**Comment by OrkunKocyigit** [comment]
Well they are examples for tooltip, sandy for example have party version of it. I don't think it will be problem to left that.

**Comment by kagekiyo7** [comment]
I got it. (Is the EX the sandy?)

**Pull request merged**
