### PR TITLE
Fix chara image link

### PR DESCRIPTION
**Pull request by kei-gbf**
Fix broken image links

キャラ画像のリンク修正です。
 
----
## Check list

- [ ] ガンダゴウザ
 - [ ] アルベール
 - [ ] バザラガ(闇)
 - [ ] レナ
 - [ ] アルルメイヤ (土)
 - [ ] メーテラ (風)
 - [ ] サルナーン (光)
 - [ ] アルタイル
 - [ ] オイゲン
 - [ ] ラカム
 - [ ] 城ヶ崎美嘉
 - [ ] リタ
 - [ ] エジェリー
 - [ ] アーミラ(SR)
 - [ ] 双葉杏
 - [ ] 城ヶ崎莉嘉
 - [ ] ウィル
 - [ ] ヤイア
 - [ ] ミュオン
 - [ ] 桜内梨子＆高海千歌＆渡辺 曜
 - [ ] サンダルフォン
 - [ ] アンチラ
 - [ ] スカーサハ
 - [ ] ナルメア (闇)
 - [ ] ヴァンピィ
 - [ ] シルヴァ (水)
 - [ ] リリィ

They are all lv90/lv100 characters.
上限解放されたキャラの画像URLが変更されてました。

### CODE REVIEW

**Comment by OrkunKocyigit** [comment]
Following files gives 404 in wiki with my current branch.
3040057000_03.png
3040045000_03.png
3040153000_03.png
3040063000_03.png
3040049000_03.png
3040122000_03.png
3040052000_03.png
3040029000_03.png
3040071000_03.png
3040183000_03.png
3040012000_03.png
3040019000_03.png
3040008000_03.png
3040007000_03.png

This branch fixes every file except 3040007000_03.png.
3040007000 seems to be Lily.
http://gbf-wiki.com/index.php?cmd=read&page=%A5%EA%A5%EA%A5%A3%20%28SSR%29&word=%A5%EA%A5%EA%A5%A3

Img url for her:
http://gbf-wiki.com/index.php?plugin=attach&refer=img&openfile=3040007000_03_full.png

**Comment by OrkunKocyigit** [comment]
Following files needs to be updated as well in order to download images.
charaImageGameURLList.txt
charaImageWikiURLList.txt

**Comment by kei-gbf** [comment]
thx! I see now, those changes were for uncapped characters lv90/lv100

**Comment by Groovman** [comment]
_full is ingame (the zoomed version of the character), the old names are correct, they are refering to the cropped version ingame, the wiki just does have those pictures. It maybe would be easier just switch how the files are exported and just check if the file has "_03" and add "_full" to it for the wiki export.

**Comment by kei-gbf** [comment]
I do not know how wiki name those files,
the suffix rule was not same.

- 3040007000_01full.png
- 3040007000_02full.png
- 3040007000_03_full.png

ah no sorry, last commit has mistake

**Comment by kei-gbf** [comment]
I edit txt_source/charaData.txt and run chara_data_converter.py
but Lilly's imageURL in charaData.json became Sarunan's

**Comment by kei-gbf** [comment]
chara_data_converter.py seem does not match "_full" image.
in the script, previous character's data was used.

3040007000_03.png was not found in wiki. (_01.png and _02.png exists)

**Comment by kei-gbf** [comment]
I got now.

- wiki does not have _03.png
- add _full suffix for _03
- character data should be _03 ? (01 was for old chara)

**Comment by kei-gbf** [comment]
I will close this PR. the patch solution was an incorrect way

the patch changed image URL _03.png -> _01.png because wiki did not have _03.png
_01.png files exists but the file was old one (lower level's image)

about _ily's patch, chara_data_converter.py did not match "_full" in charaData.txt
when image url pattern did not match, previous character's variable was used, this is another issue.

**Pull request closed without merging**
