### PR TITLE
Fix max value calc of normalElement

### PR DESCRIPTION
**Pull request by kagekiyo7**
from google form
> 進境の武器スキル合計上限は+75％ですが、上限が設定されていません（終末通常進境大SL20とネーレウスの杖通常進境中SL15を同時装備すると最大+95％になってしまう）

gamewith
https://twitter.com/Granblue_GW/status/1192816995961638915

### CODE REVIEW

**Comment by Groovman** [comment]
Please resolve conflicts :)

**Comment by Groovman** [comment]
I looked into it a bit I don't think Opus is part of the progression cap.

**Comment by kagekiyo7** [comment]
OK. Later.

However gamewith says.
image
https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/175329

**Comment by Groovman** [comment]
Nevermind gamewith is right

**Comment by Groovman** [comment]
I do the merge right now.

**Pull request merged**
