### PR TITLE
Change Lily support ability by game update

### PR DESCRIPTION
**Pull request by kagekiyo7**
image
https://xn--bck3aza1a2if6kra4ee0hf.gamewith.jp/article/show/21005

pick up
https://twitter.com/jovianshinnkai/status/1136902197503901696

### CODE REVIEW

**Comment by Groovman** [comment]
You can just change the race check to
var races = Math.min(3, module.exports.checkNumberOfRaces(chara));
and then you don't need the Math.min here anymore
totals[key]["otherBuff"] = (1.0 + totals[key]["otherBuff"]) * (1.0 + Math.min(3, races) * 0.10) - 1.0;
so it is just
totals[key]["otherBuff"] = (1.0 + totals[key]["otherBuff"]) * (1.0 + races * 0.10) - 1.0;

**Comment by kei-gbf** [comment]
```diff
- var races = Math.min(4, module.exports.checkNumberOfRaces(chara));
- totals[key]["otherBuff"] = (1.0 + totals[key]["otherBuff"]) * (1.0 + Math.min(3, races) * 0.10)
+ var races = Math.min(3, module.exports.checkNumberOfRaces(chara));
+  totals[key]["otherBuff"] *= 1.0 + (races * 0.10);
```

- [ ] 種族数チェックが２重
- [ ] 乗算の場合は(式が複雑でなければ) `*=` が使えます。（※ 未テスト）
- [ ] コミットログ: マージの時でいいので "by 4/11 game update"

**Comment by kei-gbf** [comment]
あ、見落としてた。
otherBuff は 0 based なので直接乗算するのは無理だったのかな?

**Comment by kei-gbf** [comment]
```js
var otherBuff = 1;
otherBuff *= 1.3;
otherCoeff *= otherCoeff;
```
```js
var otherBuff = 0;
otherBuff = (1 + otherBuff) * 1.3 - 1.0;
otherCoeff *= 1.0 + otherBuff;
```

hmm ... could not change the source value, otherBuff was already in a save data.

**Comment by kagekiyo7** [comment]
I Fixed  :)

**Comment by kei-gbf** [comment]
- [x] totals[key]["normalBuff"] -> totals[key]["otherBuff"]
  - [x] normalBuff is some addictive field by support ability ... could not use for this
  - [x] otherBuff is a blank field, currently no other skill/support use this. it's from user input form.

**Comment by kei-gbf** [comment]
I want to test races=4 case, where is Average(Included) field for Djeeta ?
Lily and Djeeta are both unknown race ?

**Comment by kei-gbf** [comment]
@Groovman 
I think this PR is ok
races=4 case is just extra topic. please Approve if no other issues.

**Comment by kagekiyo7** [comment]
> Lily and Djeeta are both unknown race ?

yes

image

**Pull request merged**
