### PR TITLE
Recent patches

### PR DESCRIPTION
**Pull request by Groovman**
Heyho, I added the new characters, weapons and added the parts of the recent balance patch that are know at the moment.

Also some small code clean up I did when I was bored.

### CODE REVIEW

**Comment by kei-gbf** [comment]
@Groovman 
Math min/max
I like the style, no need to write same variable/value twice.

a bit more improvement
Can you change the argument order, limit value first.
`Math.min(limit_value, value_or_expression);`

Because, given `value_or_expression` often long or contains nested formula.
limit_value first make easy to read the code.

e.g.:
- totalDA = Math.min(Math.max(totalDA, 0.0), 1.0); // nested, need to think ( ) calc order
- totalDA = Math.min(1.0, Math.max(0.0, totalDA)); // can read the code left to right straight

other solution for min/max check (just info)
- lodash library has _.clamp for min/max check
- if we can use ECMA2017. Math.clamp
  
----
- [x] `Math.max(totals[key]["tenshiDamageUP"], totals[key]["charaDamageUP"]);`
  - [x] ok, it was not a limit check.
  - [x] `totals[key]["tenshiDamageUP"] > totals[key]["charaDamageUP"]`
    - [x] does not matter ">" or ">="

**Comment by Groovman** [comment]
@kei-gbf Done
lodash clamp is just a toNumber combined with a min and a max check also using native min and max should be faster
ECMA2017 support does not look that good when I look at the compatibility matrices.

**Comment by kei-gbf** [comment]
- [ ] weapons
  - [ ] 三相女神 (Trí Bandia)
  - [ ] クラリオン (Clarion)
  - [ ] [4凸]クラリオン([4★] Clarion)
  - [ ] レインボーハンド (Rainbow Hand)
  - [ ]  ノーブルナイツ ブリジール＆コーデリア (Bridgette and Cordelia)
- [ ] chara
  - [ ] バイヴカハ (Morrigna)
  - [ ] ファスティバ(SSR)  (Ladiva (SSR))
  - [ ] キャル (Karyl)
- update balance patch
  - [x] add critical_up_own_40_50 キャル
  - [x] remove critical_up_own_10_30 "イ・タ・ズ・ラしちゃうぞ☆" カリオストロ(ハロウィンver)
  - [x] フェザー fix broken ja letter
  - [x] remove support atk_up_own_5 Nezahualpilli  ネツァワルピリ
  - [x] remove support atk_up_own_5 Charlotta (Halloween) シャルロッテ(ハロウィン)
  - [x] ファフティバ(SSR) 本物のヒーロー hp_up_own_20, txt_source
  - [x] add Jeanne d'Arc fav2 sword, txt_source ジャンヌ剣得意追加
- [ ] normalKonshinS 渾身
  - [x] TODO: no data
- [x] ex skill フラッドオブアームズ for クラリオン (Clarion)
- [x] fix some broken letters in txt_source/ and translations

----
## TODO (reported in comment)
- [ ] Nezahualpilli support skill update when confirmed
- [ ] normalKonshinS skill data

**Comment by Groovman** [comment]
Merged a recent PR and added the translations for the new characters.

**Comment by kei-gbf** [comment]
## Weapons
| en | element | type | skill1 | skill2 | skill3 |
|---|---|---|---|---|---|
| Trí Bandia | wind | wand | normalM/wind | normalHPM/wind | non/wind
| Clarion | water | gun | strengthL/water | non/water | non/water
| [4★] Clarion | water | gun | strengthL/water | non/water | non/water
| Rainbow Hand | earth | fist | normalHPM/earth | normalKonshinS/earth | non/earth

- [x] translation check gbf.wiki/Trí Bandia
- [x] translation check gbf.wiki/Clarion
- [x] translation check gbf.wiki/Rainbow Hand
- [x] all hp/attack/minhp/minattack check ... ok
- [x] normalKonshinS is TODO.

----
## Chara
| ja | en | element | race | type | fav | gender |
|----|----|----|----|----|----|----|
| バイヴカハ | [Morrigna](https://gbf.wiki/Morrigna) | wind | seisho | pecu | wand/none | female |
| ファスティバ(SSR) | [Ladiva (SSR)](https://gbf.wiki/Ladiva%20%28SSR%29) | earth | doraf | attack | fist/none | other |
| キャル | [Karyl](https://gbf.wiki/Karyl) | dark | unknown | attack | wand/none | female |
| ノーブルナイツ ブリジール＆コーデリア | [Bridgette and Cordelia](https://gbf.wiki/Bridgette%20and%20Cordelia) | light | havin | balance | sword/spear | female |



- [x] translation check gbf.wiki/Morrigna
- [x] translation check gbf.wiki/Ladiva (SSR)
- [x] translation check gbf.wiki/Karyl
- [x] translation check gbf.wiki/Bridgette and Cordelia

**Comment by kei-gbf** [comment]
@Groovman 
review done
Can you add update info to "notice.js", it's ok just template message like #216

**Pull request merged**
