### PR TITLE
Add .editorconfig file

### PR DESCRIPTION
**Pull request by kei-gbf**
EditorConfig: https://editorconfig.org/

Everyone has own editor settings,

line

In PR review, when I use gitpod.io to see the changes,
I saw often file end add/remove break-line letter,
it's unnecessary changes.

GitHub diff view on browser has Ignore Whitespaces,
but no ignore break-line. (git console has)

This config can resolve the issue by sharing settings.
This assumes the most editor/IDE supports EditorConfig.

If your editor did not support, it does not force to use IDE,
Reviewers can request to follow the coding format.

----
## Checklist

- [ ] default settings
  - [ ] charset = utf-8
  - [ ] indent _style = space
  - [ ] indent_size = 4
  - [ ] end_of_line = lf  (LineFeed)
  - [ ] insert_final_newline = true
  - [ ] trim_trailing_whitespace = true
- [ ] settings per format (which override default)
  - [ ] python scripts/*.py
  - [ ] js (JavaScript) src/**.js
  - [ ] json *.json ... 
    - [ ] I did not check under sub-directory.
  - [ ] *.md (Markdown)
    - [ ] trim_trailing_whitespace = false, it's break-line in markdown text.
  - [ ] *.yml (YAML)
- [ ] other files
  - [ ] html, css, ... use default settings
- [ ] special cases
  - [ ] app.json, package.json
         json but indent=2
  - [ ] .travis.yml
- [ ] Editor/IDE
  - [x] Atom
  - [x] Sublime Text
  - add your editor here

### CODE REVIEW

**Comment by kei-gbf** [comment]
`insert_final_newline = true`

add LF if no newline at the file end.

w/o this setting, the diff have **"newline only change"** sometime.
diff shows before/after lines around the change,
no need to contains the new line changes.

----
original file
```
aaa
file_end
```

`insert_final_newline = true`
```diff
aaa
file_end
+ new_line added
```

`insert_final_newline = false`
```diff
aaa
- file_end
+ file_end
+ new_line added
```

**Comment by OrkunKocyigit** [comment]
I use WebStorm IDE which supports EditorConfig via plugin: https://plugins.jetbrains.com/plugin/7294-editorconfig

**Comment by OrkunKocyigit** [comment]
@kei-gbf 
Are we still working on it? If not I'll recommend to close it as we have too many PRs.

**Comment by kei-gbf** [comment]
I agree too many PRs, sorry late to notice comments,
I feel a lack of review resource for numbers of PRs.
this PR was completed, the tasks were for reviewers check list.

This PR does not effect to Motocal feature at all. just developer's environment (Editor/IDE)

**Pull request merged**
