### PR TITLE
Uncaps from Patch 2019-07-17

### PR DESCRIPTION
**Pull request by Groovman**
Galilei's Insight 4* uncap

https://cdn.discordapp.com/attachments/266593284317511680/600968146068832256/unknown.png
https://cdn.discordapp.com/attachments/266593284317511680/600969267449561089/unknown.png

### CODE REVIEW

**Comment by Groovman** [comment]
Doing new characters after maintence :)

**Comment by kagekiyo7** [comment]
Is skill of rigaiBishojo enable when weapon is only main?
(reference: https://github.com/MotocalDevelopers/motocal/pull/171)

**Comment by Groovman** [comment]
Yeah forgot the Main Weapon switch :)

**Comment by h-yasha** [comment]
Possibly have rigaiBishojo as a "weapon" skill, as in "weaponCriticalDamageLimit" or something. 
just in case there's a limit for critical damage limit from weapons. since most damage limit weapon skills have a limit. (although this is a MH only weapon skill, "unique"-ish. could also "limit it" to have only 1 effective).

**Comment by kagekiyo7** [comment]
Could you add ougiRatio of Ayer 5* to chara_data_converter.py?

L496 
`patchingOugiRatio["アイル"] = {"ougiRatio": 5.0}`

**Comment by Groovman** [comment]
> Possibly have rigaiBishojo as a "weapon" skill, as in "weaponCriticalDamageLimit" or something.
> just in case there's a limit for critical damage limit from weapons. since most damage limit weapon skills have a limit. (although this is a MH only weapon skill, "unique"-ish. could also "limit it" to have only 1 effective).

Would do that when Cygames comes out with a generic crit cap up skill that skill is unique named. You can enable/disable the 2nd skill of the weapon via the main weapon switch, so weapons set to be in grid don't have the skill at all.

**Comment by kagekiyo7** [comment]
TODO: Cagliostro (Summer) Support 2
10% Bonus Water DMG effect to Water allies' critical hits on one-foe attacks.

**Pull request merged**
