### PR TITLE
#102 基礎TA率修正及びアプサラスを武器別に分割

### PR DESCRIPTION
**Pull request by kitsuki00**
#102 基礎TA率修正
アプサラス武器別に分割

### CODE REVIEW

**Comment by Groovman** [comment]
Some numbers are wrong. Class bonuses need to be (Base Value + LB bonus), for example neko it would be 6.0 as new base + 5.0 for LB => 11.0
Previously neko was placeholder (DA 6.5, TA 3.0) + LB => DA 11.5, TA 8.0, with the new bases it would be DA 11.5, TA 11.0

**Comment by kitsuki00** [comment]
thx for review !

I modified the TA bonus.

Question, does not it include MB?

There are two LB on DA (DABonus & DABonusⅡ )
It seems necessary to review DA
I post this in the issue


src
  Class4
    http://hiroxgbf.blog.fc2.com/blog-entry-24.html
    http://hiroxgbf.blog.fc2.com/blog-entry-25.html
    http://hiroxgbf.blog.fc2.com/blog-entry-16.html
  Ex2
    http://hiroxgbf.blog.fc2.com/blog-entry-26.html
```
JobBaseTaBonus = BaseTa( Base + LvBounus ) + LB
 
Class4
  beruse        : 5.0  + 5.0 = 10.0%
  sage          : 1.0  + 5.0 = 6.0%
  suparuta      : 3.0  + 5.0 = 8.0%
  warlock       : 3.0  + 5.0 = 8.0%
  chaos         : 3.0  + 5.0 = 8.0%
  gizoku        : 10.0 + 5.0 = 15.0%
  wrestler      : 20.0 + 5.0 = 25.0%
  hounddog      : 1.0  + 5.0 = 6.0%
  apsaras_spear : 20.0 + 5.0 = 25.0%
  apsaras_axe   : 15.0 + 5.0 = 20.0%
  elysian       : 3.0  + 5.0 = 8.0%

Ex2
  glory         : 5.0% + 5.0 = 10.0%
  kengo         : 1.0% + 5.0 = 6.0%
  neko          : 6.0% + 5.0 = 11.0%
```

**Comment by Groovman** [comment]
Sorry, my error the numbers in the the first commit were correct. After looking again at the formula, the base TA in the blog posts includes the level bonuses of the class and the LB stands for Limit Bonus or Extended Mastery Perks.

**Comment by kitsuki00** [comment]
add master bonus.
Handling of DA and individual setting of MB & LB
I will consult the developer.

マスターボーナスの値を加算しました。
DAの扱いや、MB & LBの個別設定に関しては
開発者に相談してみます。

JobBaseTaBonus = BaseTa( Base + LvBounus ) + LB + MB
 
Class4
  beruse        : 5.0  + 5.0 + 1.0 = 11.0%
  sage          : 1.0  + 5.0 + 1.0 = 7.0%
  suparuta      : 3.0  + 5.0 + 1.0 = 9.0%
  warlock       : 3.0  + 5.0 + 1.0 = 9.0%
  chaos         : 3.0  + 5.0 + 1.0 = 9.0%
  gizoku        : 10.0 + 5.0 + 1.0 = 16.0%
  wrestler      : 20.0 + 5.0 + 1.0 = 26.0%
  hounddog      : 1.0  + 5.0 + 1.0 + 2.0 = 6.0%
  apsaras_spear : 20.0 + 5.0 + 1.0 = 26.0%
  apsaras_axe   : 15.0 + 5.0 + 1.0 = 21.0%
  elysian       : 3.0  + 5.0 + 1.0 = 9.0%

Ex2
  glory         : 5.0% + 5.0 + 1.0 = 11.0%
  kengo         : 1.0% + 5.0 + 1.0 = 7.0%
  neko          : 6.0% + 5.0 + 1.0 = 12.0%

**Pull request merged**
