### PR TITLE
Minor Updates

### PR DESCRIPTION
**Pull request by kagekiyo7**
・Add notice
・Update translate.js
Delete "Rosetta (Grand)'s Iron Maiden (5000)" because it's duration is short, and usage rate is not high.

Change enemy resistance discription to " Unite and Fight's NIGHTMARE(25%), EX+(50%)"
https://gran-matome.com/archives/57946
https://twitter.com/Granblue_GW/status/1118104526706229248

Others

・Fix supplementalDamageBuff Field
It differed from the original behavior and the entered number was reflected immediately.

・Update notice.js
・Change input-suggest placement
・Change notation in profile

---
提案：保存タブの「スキル性能・各種計算式」表削除(更新が大変なのと、スキル効果量はスキル合計で見ることができるので)

### CODE REVIEW

**Comment by OrkunKocyigit** [comment]
Thanks. All translations and tooltips looks fine and understandable English wise. I'll approve it.

**Comment by kagekiyo7** [comment]
Thank you!

**Comment by kagekiyo7** [comment]
>Fix supplementalDamageBuff Field

I'm sorry, I thought I could fix it, but it wasn't.
The timing of reflection is different.

**Comment by kagekiyo7** [comment]
Forget writiing now（i deleted）

**Pull request merged**
